# Example GitPod configuration. You will need to adjust this for the different processes you run 
# during development

image:
  file: .gitpod.Dockerfile

ports:
  # Rails server
  - port: 3000
    onOpen: open-preview
  # PostgreSQL server
  - port: 5432
    onOpen: ignore

tasks: 
  - name: Install
    init: >
      gem update bundler && 
      bundle install &&
      bundle exec rails webpacker:install &&
      yarn install --check-files &&
      rails db:setup &&
      rails db:test:prepare &&
      gp sync-done install
  - name: Rails
    init: gp sync-await install
    command: rails server
  - name: Webpack
    init: gp sync-await install
    command: bin/webpack-dev-server
  - name: Redis
    command: redis-server
  - name: Sidekiq
    init: gp sync-await install
    command: sidekiq